// <auto-generated />
using System;
using DetectorVulnerabilitatsDatabase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DetectorVulnerabilitatsDatabase.Migrations
{
    [DbContext(typeof(DetectorVulnerabilitatsDatabaseContext))]
    [Migration("20251125204256_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("First_scanned_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Last_scanned_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.Findings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Affected_service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cve_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Scan_result_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Solution_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Scan_result_id");

                    b.HasIndex("Solution_id")
                        .IsUnique();

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.ScanResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Scan_task_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Scan_task_id")
                        .IsUnique();

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.ScanTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Asset_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Finished_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requested_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scan_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Asset_id");

                    b.ToTable("ScanTasks");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.Solutions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remediation_steps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.Findings", b =>
                {
                    b.HasOne("DetectorVulnerabilitatsDatabase.Models.ScanResults", "ScanResults")
                        .WithMany("Findings")
                        .HasForeignKey("Scan_result_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectorVulnerabilitatsDatabase.Models.Solutions", "Solutions")
                        .WithOne("Findings")
                        .HasForeignKey("DetectorVulnerabilitatsDatabase.Models.Findings", "Solution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanResults");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.ScanResults", b =>
                {
                    b.HasOne("DetectorVulnerabilitatsDatabase.Models.ScanTask", "ScanTask")
                        .WithOne("ScanResults")
                        .HasForeignKey("DetectorVulnerabilitatsDatabase.Models.ScanResults", "Scan_task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanTask");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.ScanTask", b =>
                {
                    b.HasOne("DetectorVulnerabilitatsDatabase.Models.Assets", "Asset")
                        .WithMany("ScanTasks")
                        .HasForeignKey("Asset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.Assets", b =>
                {
                    b.Navigation("ScanTasks");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.ScanResults", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.ScanTask", b =>
                {
                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("DetectorVulnerabilitatsDatabase.Models.Solutions", b =>
                {
                    b.Navigation("Findings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
